### ISSUE TITLE
Tests, acceptance & integration

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicantmaps#102]
We should create tests to ensure connecting workflows and specific component functionality.

*Integration*
 - [ ] Drawing behavior
    - [ ] Map drawing functionality works and places geometries onto map
      - [ ] (implied) We may need to encapsulate this functionality inside its own component so its behavior can be isolated from the controller
    - [ ] Buffer creation works by adding the buffer source into MapboxGL instance
    - [ ] Can click lots and save (this may need to be an acceptance test because it involves multiple components)
 
*Acceptance*
 - [x] User can search (simply type)
 - [x] Three types of project geometry types are available
 - [x] On-map drawing button is clickable
 - [x] User can click the edit project button and see new URL
 - [x] User can click to add different project _map types_
 - [x] User can toggle letter/legal & portrait/landscape
 - [x] User can click save map button in map-type editing view

**Comment by trbmcginnis** [comment]
Currently working on bottom four
