### ISSUE TITLE
Lot drawing has too many handles

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#107]
When you create a geom by selecting tax lots, the Mapbox GL Draw shape has a bunch of handles (I've seen 4-9) at each convex corner (the concave corners seem fine). So you cannot easily adjust the shape without deleting all the extra handles.

**Comment by chriswhong** [comment]
We should attempt to simplify the geometry created from the lot selection mode.  

Turf-simplify exists, so we got that going for us, which is pretty good... https://github.com/Turfjs/turf/tree/master/packages/turf-simplify

**Comment by chriswhong** [comment]
Closed by #157
