### ISSUE TITLE
Area map zoom extent should update to fit largest polygon when toggling between landscape and portrait

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#117]

**Comment by andycochran** [comment]
Perhaps the `scalePaper()` and `reorientPaper()` actions should both call `fitBoundsToBuffer()`? This would work unless the user adjusts the bearing and expects that to not be reset when changing the paper size/orientation. Tho that's probably a fine tradeoff, as I imagine paper size would/should be decided before bearing.
