### ISSUE TITLE
Land Use colors' visibility persist across maps

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#123]
The land use colors are showing when they're not supposed to _and_ not showing when they _are_ supposed to. To replicate this: 

- Do a hard refresh on the Area Map view (the land use colors show 👍)
- Navigate to the create/edit view (the land use colors show, but they shouldn't 👎)
- Do a hard refresh (the land use colors don't show 👍)
- Navigate to the Area Map view (the land use colors don't show, but they should 👎)
- Repeat… 

Seems like the land use colors have the visibility of the last hard-refreshed map. I noticed these maps have the same `id`. I suspect that `ember-mapbox-gl` is getting confused. I tried changing the Area Map's map `id` to `paper-map`, but the issue persisted. Not sure how to further debug this.

**Comment by andycochran** [comment]
😵

**Comment by allthesignals** [comment]
I think what's happening is that the data get refreshed, but because it's in an array & deeply nested, it's not destroyed and replaced. The top-level attributes on the layer-group model (`visible`) get replaced and updated each time, but not the style objects
