### ISSUE TITLE
Save Area Map Settings to Database

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#139]

**Comment by chriswhong** [comment]
The user's view and settings should be saved:
- Map center, zoom, and rotation (assuming pitch is disabled)
- Paper orientation
- Paper size

Related to #140, Save button improvements

**Comment by hannahkates** [comment]
mapCenter and mapZoom are now being written to the database in PR #169, but additional work is still needed to conditionally use those properties when a map has been saved instead of using fitBounds.
