### ISSUE TITLE
Tooltips & Guiding Text on the Project Creation/Edit Page

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#145]

**Comment by chriswhong** [comment]
Add tooltips and text for all items on the project creation/edit form.

**Comment by vvvo** [comment]
Included some welcome/introduction texts for the starting page. It's definitely just a place-holder and will probably change/be revised heavily in the future!

[Application Map Engine - Terminology Guide.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9fe10e74e7c500126c1adb/125516c66e82c728ace21e0d46c9848a2f8b80a89be0b04de470f18469632974200aa66b3dc5d72dad4f720f000311fb08482801a5addc39baa47c32d5065ebe957f5566c36f10a9bdd31de902ba74da46d1b6bc884994ef3922e4de9d532c5c5446dda0006ceacc09da52e44ae84754a1103e65e0713e7a44941b733e26.docx)

**Comment by trbmcginnis** [comment]
Small edits to the welcome text: 

"Applicant Maps provides prospective applicants with a tool for producing clear maps required under the Department of City Planning's (DCP) review of land use and environmental applications. Applications consist of a land use application form and attachments, which include maps that represent the proposed land use actions and any development that may accompany the proposed actions.

Most development in New York City is as-of-right, meaning that a proposed development must comply with the Zoning Resolution and qualify for a building permit administered by the Department of Buildings. However, projects that require special review or approvals, or modifications to existing zoning regulations are required to be reviewed by the DCP and the City Planning Commission.

Draft land use applications should still be prepared following the guidance discussed with the DCP and as described in the Interdivisional Meeting minutes.

Please visit the Applicant Portal (link) for more information regarding the review process."

**Comment by vvvo** [comment]
@hannahkates  @andycochran  Following up on today's meeting, see attached guiding questions for the "Wizard" to ask to help the user navigate the tool when creating the area map. 

[Application Map Tool - Wizard Guideline Questions.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9fe10e74e7c500126c1adb/125516c66e82c728ace21e0d46c9848a2f8b80a89be0b04de470f1846972287c2544ee6b478cf929ad463b261a061af91d010111ec98cc7ee5f2652fd41f19f1c32d1d2b9c6842e8aa880dba53bb258e1e87e0bf8a1891e16925e7898a1b391a021bdced4127e2c8159c07ab12ab1817b6192462ef7c377943941c76246a642eaafed944ca.docx)

**Comment by hannahkates** [comment]
I think this issue can be closed now. I'm storing all these docs on our google drive in the Applicant Maps folder for future reference.
