### ISSUE TITLE
Applicant can create an Area Map

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#15]
Area Attributes:
   - settings object for which layerGroups are toggled
   - orientation (print settings)

**Comment by andycochran** [comment]
Upon creating a project, the user sees “Create [Map]” buttons for each type of map. 

- Applicant clicks “Create Area Map” button, is routed to `/project/:hash/:v/area-map/`
- Applicant sees a print preview of the Area Map alongside print settings, a “Save [Area Map]” button, a “Print [Area Map]” button, and a “Back to Project” button
- Applicant can adjust the pan/zoom/bearing (PITCH IS DISABLED)
- Applicant can change the paper size (letter, legal, tabloid)
- Applicant can change the paper orientation (landscape, portrait)
- Applicant  can toggle on/off additional map layers
- Clicking “Save Area Map” button saves any changes to the settings (maybe everything autosaves and there's no need for a save button)

**Comment by hannahkates** [comment]
Done.
