### ISSUE TITLE
Use saved mapCenter and mapZoom for saved maps

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#170]
These properties are saved to the DB, but the front-end doesn't yet utilize them in rendering the area map. In order to implement that, one option would be to identify which route is active and then conditionally either fitBounds based on the project geom (for the "new" route) or set the map properties from the model retrieved from the DB ("edit" route).

**Comment by hannahkates** [comment]
This is also could be dependent on the decision on #131.

**Comment by allthesignals** [comment]
Hmm. Just ran into the two scenarios you laid out, @hannahkates. I `fitBounds` is clashing with what is set on the model, and `fitBounds` always wins out. 

Seems like we want it to `fitBounds` by default. If the applicant-map model's `mapCenter` and `mapZoom` values are set, those should be used instead.

**Comment by allthesignals** [comment]
Sounds like we really just want one source of truth on this. `center` and `zoom` can be calculated from the bounds. I think this would be easier if we were only setting on of these things, then deriving other values from that.
