### ISSUE TITLE
User can create a new project

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#18]
User clicks “Create a new project”… 
_section 1 expands to show project UI_
_OR user is routed to the_ `/project/` _view  for creating a project_

- User sees a text input (project title), map, and "Save Project" button (disabled until valid title and geometry exist)
- User adds project title text
- User defines project geometry on map by either
…drawing a polygon
…select lots (joined to create polygon?)
- User sees "Save Project" become active
- User clicks "Save Project" — routes to `/project/:hash/:v/`

**Comment by hannahkates** [comment]
Done
