### ISSUE TITLE
Proposed Rezoning label should be bolded on the area map

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#181]
When a user creates or new district or changes the label for an existing district, those new labels should be bolded. This requires updates to the label styling and the legend.

**Comment by hannahkates** [comment]
TRD has agreed bold text is okay instead

**Comment by allthesignals** [comment]
Okay. This sounds like a universal styling change? Let's attempt to make this a universal style change before we need to make it data driven.
