### ISSUE TITLE
Add annotations

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#186]
Work involved:
- [ ] Adding and saving the annotations as a single feature collection on the model
- [ ] Adding the annotation feature collection on the API
- [ ] Creating the draw tools for annotations
- [ ] Including the annotation draw tools on each of the geometry-edit routes
- [ ] Display the saved annotations on all the geometry-edit routes
- [ ] Display the saved annotations on the project dashboard preview map
- [ ] Display the saved annotations on the area map
- [ ] Add annotation tests

Four types of annotations are needed. See screenshot below for the list.
![IMG_20181218_104724.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593ac159e983f40020992a93/125516c66e82c728ace21e0d46c1b9bd1cd0d3f8d7b8ed12fc62a1c47d1175276b48e13b628ae92dbc56395b4d5a1cad445d0e46aafa897ff7bf68708a5e0eb9d6695877932f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e38e8e4a3f1c061c8ef95927ed.jpg)

**Comment by allthesignals** [comment]
Adding @andycochran google doc: 
https://docs.google.com/document/d/1XFLa5HWfkKo9RXR4Bc2mCVww4u8hLY1jp2O9v5HSRBs/edit#

Outstanding questions:
Do users need to make annotations while in lot selection mode?
Should annotation tools be available on the dashboard view, or can users only edit annotations in geometry-edit view?
Can we create GIFs for each of these tools? 
Can we make sure all annotation labels always show and do not avoid collision with other labels (e.g. street names)

**Comment by allthesignals** [comment]
We'll need a way to distinguish between annotation features and features intended for analysis. 

Either feature collections could have a separate type property or we just use an entirely different feature collection. The former could help distinguish which parts of the feature collection are consisdered for analysis (intersection questions, etc). The latter approach could contain all annotations, but those annotations are specific to a given attribute. 

The issue with the latter is that it introduces new structure to the model schema, but it might be the best approach.

**Comment by andycochran** [comment]
> We'll need a way to distinguish between annotation features and features intended for analysis.

AFAIK, all the custom draw tools are for annotations and should be visualized on the output PDF maps. Was there a request for a feature allowing analysis tools? Couldn't the user (e.g.) delete lines they drew to temporarily measure/analyze? 

> … pretty important to know [on which views annotations tools are available] 

I will confirm this with the customer. Is this blocking development, or can we easily add annotations to the lot/dashboard views later?

**Comment by allthesignals** [comment]
> I will confirm this with the customer. Is this blocking development, or can we easily add annotations to the lot/dashboard views later?

@andycochran welcome back! Hmm not particularly. It might be. There are lots of moving parts but I'm trying to make this modular enough so we can add as-needed.
