### ISSUE TITLE
User can share a project URL

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#19]
User clicks “Share Project” button, a modal shows copy-to-clipboard input/button (as with City Map share button). This button should be available on the project dashboard.

**Comment by hannahkates** [comment]
Based on the demo today, this sounds like it's still in high demand and has been useful in other apps. Moving it to higher priority for our next sprint.

**Comment by hannahkates** [comment]
@andycochran The email button in #324 mostly accomplishes this, but some users may prefer to copy/paste instead of having their mail app open up. Thoughts on this issue vs. #319?

**Comment by andycochran** [comment]
Yeah, I noted in 324 how the UI could be improved w/ a copy button. If my suggestions are incorporated there, it'll close this issue. 

319 might be a separate issue. Perhaps 324's popover message could prompt folks to bookmark the project. But I'm not convinced we need to add any UI/buttons for bookmarking.
