### ISSUE TITLE
User should not be able to draw while selecting tax lots

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#192]
Currently, the draw controls remain available while you're in tax lot selection mode. This means you can draw a complicated shape while unknowingly in the wrong mode, then lose your work when you click "Make Selection." Instead the draw controls should hide while in tax lot selection mode.

**Comment by andycochran** [comment]
The `lotSelectionMode` boolean is used to hide the draw instructions. This could be of use?

**Comment by hannahkates** [comment]
No longer an issue with refactor of geom creation work flow
