### ISSUE TITLE
Some tax lots selecting as partial geometry

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#198]
When selecting some tax lots, only part of the geometry is filled in with yellow.

**Comment by trbmcginnis** [comment]
![Screen Shot 2018-10-21 at 11.41.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1a8ed004e6dd00118290e2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f26b7191a379ee0c2f50415b4ebc21254d58eeb9cb74fce36f34985619e8836c5a71973f47afb8d64eb655ba20894ad1b1b88d4f95fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe14c52ad1b3461e770366e0a.png)

**Comment by allthesignals** [comment]
CLosed by #202
