### ISSUE TITLE
Hovering tax lots only works at certain zoom levels

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#204]
I believe this is related to the tile clipping bug.

To replicate… 
- Zoom in until tax lots are just visible
- At zoom this level, most tax lots are not clipped as they're contained within 1 tile
- Hover multiple adjacent tax lots, the tooltip updates appropriately
- Now, zoom in so that tax lot hovers are clipped by the tile bug
- Hovering at this zoom level causes the tooltip to break — it gets stuck until you hover onto another tile

**Comment by hannahkates** [comment]
Closing, this appears to be resolved now
