### ISSUE TITLE
Allow transition from lot selection mode to draw mode

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#216]
When the user hits save or "next step", several things should happen depending on the user's stage in the process:
- [x] Always: the correct geometry (matching the type param in the route) should be written to the database.
- [x] After development-site and rezoning-area are each saved: the user should be directed to the updated currentStep route
- [x] For the rezoning geoms: the user should be directed to the next rezoning geom they need based on their boolean answers.
- [ ] From the lot selection mode: users should have the option of transitioning to the drawing mode to make adjustments to the unioned geom of the lots they've just selected

**Comment by hannahkates** [comment]
@allthesignals is any of this already covered in what you're doing for #202?

**Comment by allthesignals** [comment]
>  From the lot selection mode: users should have the option of transitioning to the drawing mode to make adjustments to the unioned geom of the lots they've just selected

This doesn't really appear in the mockup - what is the UI for this?

**Comment by allthesignals** [comment]
>  For the rezoning geoms: the user should be directed to the next rezoning geom they need based on their boolean answers.

I believe this is issue #240.

**Comment by allthesignals** [comment]
Add button in sidebar that says "Manually Edit" which switches to draw mode - can't go back!
