### ISSUE TITLE
Automatically generate rezoning area polygon for the user

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#227]
Ideally, we should be able to use the edits the user made to the existing zoning layers to create a polygon that highlights the area captured within  those changes. If we can figure out how to do this for the user, it will remove a step for them.

If not, we will have to create an addition geometry-edit step type for the user to trace around their proposed zoning changes.

**Comment by allthesignals** [comment]
https://github.com/NYCPlanning/labs-applicantmaps/pull/236 <- @chriswhong working on this but we will need to work together to reconcile his new feature with structural changes

**Comment by allthesignals** [comment]
This is super unstable so we should probably create some test cases or tests or something as insurance
