### ISSUE TITLE
Add instructions on sidebar for each step

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#231]

**Comment by trbmcginnis** [comment]
Different draw instructions for each type (e.g. development site) and mode (lot vs. draw) on geometry-edit route

**Comment by trbmcginnis** [comment]
This is dependent on having TWO separate draw controls--one for each mode (lot vs. draw). Right now the draw controls still have BOTH  "draw" and "lot" available regardless of the query params that specify the type of mode--once this is changed, add in instructions based on type and mode. Reference the sketches: https://docs.google.com/drawings/d/1v_v5JrK7HMbL0U8aSzK6IXdIEAQMZ3WHZvFeLbfovVg/edit

**Comment by allthesignals** [comment]
In https://github.com/NYCPlanning/labs-applicantmaps/pull/236, there are components under `project-geometry-edit` for each type, and in those templates, there's space to deal with writing instructions

**Comment by trbmcginnis** [comment]
Amazing , thanks!
