### ISSUE TITLE
Handle transition between rezoning geom editing

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#240]
There is some unexpected behavior if the user only selects "Yes" for one of the types of rezoning. The app redirects them back to the rezoning questions route after they've saved their geom instead of taking them to the dashboard.

**Comment by hannahkates** [comment]
@allthesignals this is all implemented already, right?

**Comment by hannahkates** [comment]
@allthesignals ^ I just updated the description for some unexpected behavior in the transitions from the rezoning geom-edit pages. Let me know if you want me to clarify anything.

**Comment by allthesignals** [comment]
@hannahkates can you add test cases for these scenarios

**Comment by allthesignals** [comment]
> When a user selects "yes" for either commercial OR special districts, after creating the geom, they are redirected back to projects/:id/edit/rezoning instead of the completed dashboard.

I don't understand what this means - they select "yes" for either of those and no for everything else?

**Comment by allthesignals** [comment]
Going to check this out now

**Comment by allthesignals** [comment]
The first scenario was caused by the inconsistency you noticed this morning @hannahkates thx

**Comment by allthesignals** [comment]
> When a user selects "yes" for commercial AND special districts, after creating the geom for the first one, they are redirected back to projects/:id/edit/rezoning and aren't able to access the geom-edit step for the next geom they need.

I've added a test case for this, but there may be additional weirdness caused by the usage of static `link-to` in the templates.
