### ISSUE TITLE
Don't save rezoning geoms if user hasn't made any edits

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#245]
When you are on the dashboard and haven't previously created rezoning geoms, if you click "add" the app automatically saves the queried zoning as the geom, even if the user doesn't make or save any edits.

Steps to recreate:
1. Create project that doesn't require rezoning
2. On dashboard click "add" for one of the rezoning layers
3. On the geometry-edit page, don't do anything, just look at the page
4. Hit the back button on the browser to go back to the dashboard
5. The model will now contain an object for the rezoning geom and the dashboard UI now says "edit" for the geometry type instead of "add" even though you didn't mean to save anything

**Comment by allthesignals** [comment]
Can you check that this is still happening? I manually tested it, and I see rollback gets called when transitioning out of the route.

(Separately: we should think about dialogue that asks the user if they want to navigate away - @chriswhong does this mean the dreaded `alert()`?!)

**Comment by hannahkates** [comment]
It does't appear me happening anymore. @allthesignals When you say dialog, are you imagining come kind of pop up that warns a user that their changes won't be saved if they go back?

**Comment by allthesignals** [comment]
> When you say dialog, are you imagining come kind of pop up that warns a user that their changes won't be saved if they go back?

Yes - gmail does this, for example

**Comment by andycochran** [comment]
I can't replicate this because of another issue. When I get to your step 4 (back button to go to dashboard), I am redirected to the rezoning question wizard step. I think once you've seen the dashboard, no redirection should ever happen again, right?

**Comment by allthesignals** [comment]
@andycochran 

>  I think once you've seen the dashboard, no redirection should ever happen again, right?

If that's what the best user experience is, then let me know when you decide because that will require some new properties on the model.

**Comment by allthesignals** [comment]
> When you are on the dashboard and haven't previously created rezoning geoms, if you click "add" the app automatically saves the queried zoning as the geom, even if the user doesn't make or save any edits.
> 
> Steps to recreate:
> 
> 1. Create project that doesn't require rezoning
> 2. On dashboard click "add" for one of the rezoning layers
> 3. On the geometry-edit page, don't do anything, just look at the page
> 4. Hit the back button on the browser to go back to the dashboard
> 5. The model will now contain an object for the rezoning geom and the dashboard UI now says "edit" for the geometry type instead of "add" even though you didn't mean to save anything

This would make a great acceptance test

**Comment by allthesignals** [comment]
The original issue doesn't happen anymore but I can confirm what @andycochran is seeing. Should there be a separate issue?

**Comment by andycochran** [comment]
> If that's what the best user experience is, then let me know when you decide because that will require some new properties on the model.

Yes. This is what I tried to communicate with the "Are all Qs answered?" step in the flow diagram (sorry if that wasn't clear): 

<img src="https://user-images.githubusercontent.com/409279/49181990-005a6b80-f327-11e8-85f2-d34bf22e97ae.png" width=250 />

If you've seen the dashboard, then you've answered all the questions, and you should not be redirected to the wizard.

**Comment by allthesignals** [comment]
> > If that's what the best user experience is, then let me know when you decide because that will require some new properties on the model.
> 
> Yes. This is what I tried to communicate with the "Are all Qs answered?" step in the [flow diagram](https://docs.google.com/drawings/d/1EJk3sAPE-L2I61sMLtXExai6eCqBADFtwGwVrc62Ga8/) (sorry if that wasn't clear):
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/409279/49181990-005a6b80-f327-11e8-85f2-d34bf22e97ae.png">
> 
> If you've seen the dashboard, then you've answered all the questions, and you should not be redirected to the wizard.

Sounds good! It sounded like you were unsure there so wanted clarification. Thanks!
