### ISSUE TITLE
Don't highlight lots in any of the mode=draw geometry-edit maps

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#249]

**Comment by trbmcginnis** [comment]
I think we originally wanted to keep `highlightable: true` for lots in `mode='draw'` because it helps the user know which tooltip belongs to which lot. Right now we have "lot" labels on the layer, and the tooltip shows extra info: the address and full BBL of the highlighted lot.

**Comment by hannahkates** [comment]
Closing, this appears to have been implemented already and we haven't heard any recent complaints from users.
