### ISSUE TITLE
Turn off ability to drag shapes around

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#254]

**Comment by trbmcginnis** [comment]
When a user clicks in the middle of a shape, they can drag the entire shape. Turn this off, not really useful for our purposes

**Comment by allthesignals** [comment]
Will probably have to set up a custom mode: https://github.com/mapbox/mapbox-gl-draw/issues/753

**Comment by allthesignals** [comment]
Could probably just override this hook with noop: https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/MODES.md#modeondrag

**Comment by trbmcginnis** [comment]
**One Option:**

So mapbox has two different [modes](https://github.com/mapbox/mapbox-gl-draw/issues/276) for selecting draw features: `simple_select` allows users to quickly select and drag multiple features whereas `direct_select` allows users to edit the shape of a single feature. When selecting and editing draw features in applicant maps I noticed that:

A - user clicks once on map and moving cursor --> pan map
B - user clicks once on feature and letting go --> vertices show up but cannot be edited, drag cursor shows up and users now have the option to click and drag the feature
C - user clicks again on feature --> users now have the option to edit vertices (whereas they didn't before with the first click on the feature), users can still drag if they want to
D - user edits vertices --> now the user no longer has the ability to DRAG the feature, instead clicking and moving the cursor pans the entire map
E - user clicks shape after editing vertices--> user is now back in mode where they can see the vertices but cannot edit them, they CAN drag the shape if they want to

^^trying to see if there is a way with `this.draw.changeMode('')` to change to a mode where the user clicks ONCE on the shape and can immediately edit the vertices, but CANNOT drag the shape (much like mode D above. 

**Another less good option:**

Checking for event has been triggered with `MODE.onDrag` (user has started dragging the shape). Then make interactions with the shape `static`. When MODE.onDrag is no longer happening, make interactions with the shape `active`. 

[MODE.onDrag](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/MODES.md#modeondrag)
Triggered when a drag event is detected on the map

Parameters

state {Object} - a mutible state object created by onSetup
e {Object} - the captured event that is triggering this life cycle event

**Comment by andycochran** [comment]
> …Would transitioning into `direct_select` mode when a feature is selected work for you? Really all `simple_select` does is let you select multiple things, move and delete them. If you don't need to work with multiple features, then I'd say listening for `draw.selectionchange` and maybe `draw.modechange` and moving to `direct_select` with `draw.changeMode()` should work for you.
https://github.com/mapbox/mapbox-gl-draw/issues/667#issuecomment-314133570

**Comment by andycochran** [comment]
```
    mapInstance.on('draw.selectionchange', () => {
      const mode = draw.getMode();
      const selected = draw.getSelectedIds()[0];

      if (selected && mode === 'simple_select') {
        draw.changeMode('direct_select', { featureId: selected });
      }
    });
```

**Comment by theenoahmason** [comment]
Coming from Mapbox GitHub where this is referenced, **BRILLIANT**. Thank you.
