### ISSUE TITLE
Allow users to edit the Rezoning Boundary themselves

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#257]
After the rezoning boundary has been calculated, allow the user to go back and edit this boundary to make it fit regulations. Add explanatory language for this in the instructions.

**Comment by hannahkates** [comment]
Once #227 is implemented, we should check that the geom is created by the app, displayed on the project preview map, and appears as editable on the dashboard. In the demo, it sounded like this way of accessing the rezoning area edit mode via the dashboard should be sufficient.

**Comment by allthesignals** [comment]
To-do:

Geometry edit works but needs content for the sidebar

**Comment by andycochran** [comment]
This was done in #259.
