### ISSUE TITLE
Instructions for re-doing lot selection

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#258]

**Comment by trbmcginnis** [comment]
We are not actually saving which lots are selected but instead just creating a boundary around the selection. When attempting to go back and add new lots to their selection, users need to re-select ALL of the lots that are part of their project. We should explain this to users.

**Comment by hannahkates** [comment]
@chriswhong @allthesignals How hard would be it reselect their tax lots for them each time they go to that route to avoid this problem?

**Comment by hannahkates** [comment]
Combining with #308
