### ISSUE TITLE
User can create and edit 3 different types of project geometry

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#27]

**Comment by chriswhong** [comment]
There are three types of geometries associated with the Area map.
- Development Site Boundary (Where actual building will take place) 
- Project Area Boundary (All tax lots subject to any of the proposed actions)
- Rezoning Area Boundary (All tax lots subject to the proposed rezoning) (Only applicable if the action is a rezoning)

**Comment by andycochran** [comment]
https://docs.google.com/drawings/d/1E-FbCU0_BGctsP_8ubiDvQDH64wpQSrFElKcrAFAHrY/edit?usp=sharing

![image](https://user-images.githubusercontent.com/409279/45703858-75e5d680-bb43-11e8-90c6-41aadf411ac7.png)

**Comment by allthesignals** [comment]
^ @andycochran this looks like one map in which the buttons simply change the state of the map and the model? So adding a development site will trigger the tax lot selection functionality that @chriswhong is working on. Is that right?

**Comment by chriswhong** [comment]
When the user is creating a geometry, they will have the manual drawing tools AND the tax lot selection at their disposal.  Think of the tax lots as a drawing mode.

**Comment by allthesignals** [comment]
@chriswhong okay thanks - I think I am asking more broadly about how the views should work.

**Comment by andycochran** [comment]
I think this is just one view that shows/hides components for drawing purposes. 

I've pushed up branch `27-crud-geoms` that has a prototype of this UI.

**Comment by andycochran** [comment]
(My prototype has a lot of repeated code that can be moved into components for drawing and lot selecting.)

**Comment by chriswhong** [comment]
Routing is set up to go back to a project's create/edit page from the dashboard, but it is not possible to edit existing geometries (both in create and edit view).

**Comment by chriswhong** [comment]
Closed by #125
