### ISSUE TITLE
Geometry-edit undo issue

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#271]
When a user has saved a geometry and comes back to edit it, the undo button doesn't behave as expected. Instead of undo resetting back to the saved geom each time, it saves previous edits that weren't saved and includes those each time the user select an additional lot to add to their collection.

I think the gif below captures it well:
![undo issues](https://user-images.githubusercontent.com/13967925/49100185-5228c600-f241-11e8-862e-37f07299caec.gif)

**Comment by hannahkates** [comment]
@allthesignals you mentioned that you found a cool library that helps with tracking history for undo behavior. Would that help with solving this?

**Comment by allthesignals** [comment]
@hannahkates yes - I am working on adding that now. The addon needs to be upgraded, I am almost finished with it (see https://github.com/offirgolan/ember-time-machine/issues/124)

As for the behavior you're seeing, I'm not sure why it does that - the undo button triggers `rollbackAttributes()` which should reset the geometry to what it was before any changes were made.

**Comment by hannahkates** [comment]
"Undo" should be renamed to say "Reset" instead.

**Comment by hannahkates** [comment]
I'm observing another unexpected behavior for the undo/reset button from a rezoning edit page. If the user hits undo when they haven't made any changes, the button changes the template somehow, providing a blank pane on the left side. The route stays the same, even though the template changes. 
[Undo issue 2.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593ac159e983f40020992a93/125516c66e82c728ace21e0d46dd9a9e2cc28aba9cfcba03f61fbcd6395428792c07b7692ac7b62aee172e005d094dac15095610fcf98b2ef2b13877890919f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b8894fc4ed3e25e2898e4f2c53.gif)

**Comment by allthesignals** [comment]
> I'm observing another unexpected behavior for the undo/reset button from a rezoning edit page. If the user hits undo when they haven't made any changes, the button changes the template somehow, providing a blank pane on the left side. The route stays the same, even though the template changes.
> 
> [Undo issue 2.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593ac159e983f40020992a93/125516c66e82c728ace21e0d46dd9a9e2cc28aba9cfcba03f61fbcd6395428792c07b7692ac7b62aee172e005d094dac15095610fcf98b2ef2b13877890919f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b8894fc4ed3e25e2898e4f2c53.gif)

truly horrifying D:

**Comment by hannahkates** [comment]
I'm moving this back to inbox until we implement the undo/reset functionality again.

**Comment by hannahkates** [comment]
Closing in favor of #412
