### ISSUE TITLE
Add Area Map Legend

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#28]

**Comment by chriswhong** [comment]
Add a dynamic legend to the Area Map

- Vinh to provide current sample of Area Map Legend

**Comment by vvvo** [comment]
![SAMPLE - Area Map with Rezoning (with SD).jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9fe10e74e7c500126c1adb/125516c66e82c728ace21e0d46dbb5b713aea6e9c2a99e51a15cb0b9285667642010ab6b4280f927b14b75064f4709f505004f2788e09b37b4f67e2fd00958a9c3674d71943c14a9e98049bc01ee71821b85b6be8f18c7ec3a26b299935d7c4f5b4cd6a2047ff5db59c24af74ceb4c50a7143367e670307c46971a6761.jpg)

Apologies for the delay on this! Had to make some tweaks to the legend. Please note that for the special district, a light stipple pattern of a shade would be sufficient.
