### ISSUE TITLE
Handle empty rezoning geoms

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicantmaps#284]
In some situations a given development site will not have proximate rezoning geometries. This means Carto will return an empty FeatureCollection, which our app treats as "empty". Further, our validator also believes it is empty. But, there isn't any relevant zoning in the area. 

We will need handling for this. I'm not sure what the UI for it should be. Maybe a warning message?

**Comment by allthesignals** [comment]
Yeah, I think I was confused for a minute because I didn't think that people might be _adding_ a zoning overlay by drawing it. But essentially my concern is that:

User says "yes, I need special purpose districts rezoning", and then they see a blank map. It's probably more obvious to them than it is to me that they should draw something, but *unless they draw something, they cannot move forward*, which is what I want to confirm.

**Comment by andycochran** [comment]
I think that's okay. For now, at least. We'll note in user testing if it gives anyone trouble. 

But a "back" button would help in this case. Tho it'd need to be conditional, knowing the previous route (back to the dashboard, or back to the previous zoning type drawing, or back to the zoning wizard question).

**Comment by allthesignals** [comment]
Would that back button be "back to current step"? Which would be the dashboard?

**Comment by andycochran** [comment]
I think if we added a back button to the `geometry-edit` view, the logic would need to be… 

- `if` all questions are answered `&&` all chosen zoning types have geoms
  - go to the dashboard
- `else if` you're currently editing a zoning type that's not the first of your chose types
  - go to the previous type's `geometry-edit` view
- `else`
  - go to the wizard question

**Comment by andycochran** [comment]
(The browser back button should probably function the same way.)

**Comment by allthesignals** [comment]
> I think if we added a back button to the `geometry-edit` view, the logic would need to be… 
> 
> * `if` all questions are answered `&&` all chosen zoning types have geoms
>   
>   * go to the dashboard
> * `else if` you're currently editing a zoning type that's not the first of your chose types
>   
>   * go to the previous type's `geometry-edit` view
> * `else`
>   
>   * go to the wizard question

Yeah, this is how the `currentStep` functions

**Comment by hannahkates** [comment]
From reading through this, it sounds like we're agreeing that there should be a back button on the geometry-edit routes that takes the user to currentStep. I'll create a separate issue for that. It sounds like the handling of empty rezoning geoms isn't actually a problem so far, so I'll close this.
