### ISSUE TITLE
Step indicator isn't updating to reflect current step

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#292]
The current step indicator at the bottom of the left hand pane in the wizard is no long updating to show the current step.

**Comment by andycochran** [comment]
@hannahkates Can you outline the steps to reproduce this bug as you've seen it. I think I might be seeing something different.

**Comment by hannahkates** [comment]
@andycochran I think the behavior has changed since this the bug was created. It looks like it is following the sequence correctly except for the project area = no behavior that you noted where the step immediately updates to rezoning. The step shouldn't update until the user hits next.
