### ISSUE TITLE
Consider stable, valid geometries over randomly generated

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicantmaps#303]
At times the test suite will fail because the randomly generated geometries are invalid - there can be a linear ring intersection or an unclosed polygon gets drawn. It happens rarely but can be annoying at times.

We should think about including some test geometries that we know are valid.

**Comment by hannahkates** [comment]
1. https://applicantmaps-api-staging.planninglabs.nyc/project/MT97XqCWJMTX5FdaE%2FkG
2. https://applicantmaps-api-staging.planninglabs.nyc/project/2hu85a4jmJbUI7tmqTxx
3. https://applicantmaps-api-staging.planninglabs.nyc/project/HyQCjWlb7kA8gI%2FienZI (rezoning area isn't showing up for this one, but maybe there's a lag)

**Comment by allthesignals** [comment]
Thanks @hannahkates

**Comment by allthesignals** [comment]
This is done - thank you @hannahkates
