### ISSUE TITLE
Show dotted line as 600ft from the union of all three polygons

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#31]
The dotted extent line should be drawn as 600ft buffer from the union of all three polygons (development, project, and rezoning areas)

**Comment by allthesignals** [comment]
Waiting on more specifics from @andycochran @chriswhong - I don't know if it makes sense to start on this without understanding how the other related change maps will be implemented.

**Comment by chriswhong** [comment]
I think we can work on this now that we have all three user-created geometries in the model
