### ISSUE TITLE
Write test ensuring copy URL button performs

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#339]
When trying to write this test, we ran into issues with the test not being able to find the copy-button within the ember-popover modal. We need to figure out how to find the button so its functionality can be tested.

User work flow to test:
- User clicks "Share Project" button inside the project-setup-status component
- Modal (ember-popover) appears
- User can click "Copy Link" button
- Link gets copied to clipboard
- Link takes user to a valid page

ember-cli-clipboard provides its own testing helpers:
https://www.npmjs.com/package/ember-cli-clipboard

**Comment by chriswhong** [comment]
I don't think we need to test the functionality of ember-popover or ember-cli-clipboard, which is all the share button really is.  There is a test in the new `share-button` component to make sure it renders a passed-in label, but the rest of the functionality is based on the two addons above and trusting that `window.location.href` works.
