### ISSUE TITLE
Bug with tooltip when hovering over tax lots

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#365]
When hovering over tax lots in the lot selection mode, the tooltips don't appear on the map. However, if you hover over a lot that's close to the left pane, the tooltip shows up inside the left pane. Screenshot:
![image](https://user-images.githubusercontent.com/13967925/51075847-2893f480-165f-11e9-9941-d6c7b876876b.png)

**Comment by andycochran** [comment]
I thought this was a `z-index` bug. After a bit of investigating, turns out it's a `position` bug. This should be fixed in `ember-mapbox-composer`, which uses `.map-tooltip { position: absolute; }`. That should be changed from `absolute` to `fixed` so that the tooltip is relative to the viewport instead of its closest positioned parent.

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/52650947-43a19080-2eb9-11e9-8321-f2f2be03d684.png)

It also seems like there's too large a gap between the hovered item (yellow BBL) and the tooltip.

**Comment by andycochran** [comment]
Applicant Maps is using `"ember-mapbox-composer": "0.0.21",` but v0.2.3 is the latest. Tooltips seem to work fine in the Composer dummy app. So we should get this app on the most current version of Composer before trying to address this tooltip bug.

**Comment by andycochran** [comment]
I tried updating Composer; doesn't fix the bug. Upon further investigation, I think the reason for this is that the `{{layers.tooltip}}` component being rendered in `lots.hbs` is in the sidebar, not the map. So it's absolute positioning is relative to the sidebar. We might need a wormhole for it?

**Comment by andycochran** [comment]
This got fixed for free w/ #384.
