### ISSUE TITLE
[Annotations] prevent adding vertex 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#366]
User should not be able to add a vertex (by clicking midpoint) to an annotation line or this happens: 

![image](https://user-images.githubusercontent.com/409279/51121474-8eaa8400-17e5-11e9-88a8-9008017c47a1.png)

**Comment by allthesignals** [comment]
@andycochran this will probably require rewriting some of the mode functionality, takes longer than anticipated. Should I keep spending time on fixing? Any alternatives I could try or should I keep pushing?

**Comment by andycochran** [comment]
It might be possible to fix this with styling changes. If we add a custom style that hides the midpoint, the user will not be able to click on it to add a third vertex.
