### ISSUE TITLE
[Annotations] missing arrows

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#367]
Sometimes arrows don't show up at the ends of annotation lines. I think this is a collision issue, since when they're missing I can make them appear by changing the zoom level. We should adjust the style so the arrows always show. 

![image](https://user-images.githubusercontent.com/409279/51121750-2dcf7b80-17e6-11e9-9b8e-2448d408b7c0.png)

![image](https://user-images.githubusercontent.com/409279/51121759-358f2000-17e6-11e9-82a6-af2b04b49e85.png)

**Comment by allthesignals** [comment]
You're right, it's definitely a collision issue.
