### ISSUE TITLE
[Annotations] changes should enable save button

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#368]
If you change annotations but not the zoning, you’re not prompted to save. The save button stays disabled. This is probably desired for the first time you edit the zoning. But of a user goes back to a particular zoning and only changes the annotations, they should be able to save.

**Comment by andycochran** [comment]
Related to #380 and the idea of always saving changes w/o explicit action.

**Comment by allthesignals** [comment]
Saving an annotation is blocked by this: https://github.com/NYCPlanning/labs-applicantmaps/blob/develop/app/components/project-geometries/types.js#L74-L106

One word of caution is the rezoning calculation... this is a validation to protect the rezoning calc, which is a sign that the rezoning calc should probably defend itself more. 

This is also becoming way more of a model-level validation, but I think I had problems doing that for some reason (

**Comment by julialucyhogan** [comment]
This was achieved in Matt's back button refactor -- changes to geometry are no longer required for progress when editing completed map, so annotations can be added via edits to completed map & saved!
