### ISSUE TITLE
Add Optional Projectid field

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#37]

**Comment by chriswhong** [comment]
Can be used to add labels to the map so people can lookup the project in ZAP search, etc.

**Comment by allthesignals** [comment]
I think we have a [projectId](https://github.com/NYCPlanning/labs-applicantmaps/blob/develop/app/models/project.js#L23) for the model - is this just a freeform field or do we need some typeahead guidance thing? I'm guessing the former.

**Comment by allthesignals** [comment]
And assuming this "Zap-y" "projectId" should go on the Project model

**Comment by allthesignals** [comment]
![Screen Shot 2018-09-17 at 4.54.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f46b7191a37cf1172f4f5f585ecc3c4a4356bcbbd671f3e57862804e0ebfd0685a25c46b12acecd316eb01ba228e1b82b2bb8919d2f42f67b6d5db1063474f4dcbed5727a19041c95df54ce34c52a2153761e0752431.png)
