### ISSUE TITLE
[Annotations] Editing length of straight/curve lines should update their label

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#375]
The line annotations are only updating their label on creation. When you edit them, changing the distance, the label remains the previous measurement.

**Comment by allthesignals** [comment]
This a bigger issue in my mind bc there is a problem with the full _lifecycle_ of creating/editing these lines. The process isn't cyclical, it ends in a totally different state that when it begins.

**Comment by allthesignals** [comment]
We need to read up on the custom modes documentation: https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/MODES.md
