### ISSUE TITLE
[Annotations] Label collision causes missing info

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#377]
One annotation can cause another's label to not show. Whichever feature was created later trumps the previous ones. Perhaps all annotation labels should ignore collision detection. 

![image](https://user-images.githubusercontent.com/409279/51401221-3ee6f800-1b18-11e9-9ce3-f0cb87851f39.png)

**Comment by andycochran** [comment]
Relatedly, we should work out how to prioritize all label collision. 

![image](https://user-images.githubusercontent.com/409279/51401577-1a3f5000-1b19-11e9-9c28-663a0f105cdd.png)

**Comment by hannahkates** [comment]
Related to #367

**Comment by andycochran** [comment]
This will be closed by #432, which ignores collision for all annotations… 

![image](https://user-images.githubusercontent.com/409279/53256991-25951680-3697-11e9-9583-48efa22cf114.png)
