### ISSUE TITLE
[Annotations] Don't show measurement for right angle

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#378]
While creating a right angle annotation, before clicking the 2nd point, it displays a measurement. This measurement should not be shown. 

![image](https://user-images.githubusercontent.com/409279/51404989-0862aa80-1b23-11e9-94d2-a802193697a1.png)

**Comment by allthesignals** [comment]
There's a "wrong" way to do this which is some if/else logic that knows the current model and short-circuits.

**Comment by hannahkates** [comment]
Make sure this is fixed in #375
