### ISSUE TITLE
Inline edit of dashboard doesn't persist to server

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-applicantmaps#380]
Inline edit of things like project name in the dashboard view does not trigger a save.

**Comment by allthesignals** [comment]
It happens here, in the project dashboard view: (projects/:id):

<img width="353" alt="image" src="https://user-images.githubusercontent.com/5004319/53347838-ed384700-38e7-11e9-81f0-c675f1228763.png">

**Comment by allthesignals** [comment]
May be due to the `save` button not triggering an actual POST to the API?

**Comment by andycochran** [comment]
This is related to other save states: 
- Changing print settings 
- Editing annotations w/o changing zoning

After the last meeting w/ the customer, @hannah and I discussed replacing all the save buttons in the with wizard with "prev/next step" buttons and saving changes to geoms and annotations w/o explicit action. The print settings could also be saved on change.
