### ISSUE TITLE
[Annotations] Centerline icon should be at the end of an annotation arrow

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#383]
There isn't always room for the centerline icon to fit nicely where it belongs on the map. TRD wants users to still be able to point out where the centerline is by drawing an arrow to it when the CL icon annotation at the end. Picture attached.

![image](https://user-images.githubusercontent.com/13967925/51790016-cdcdc300-215d-11e9-8141-6ed029baecda.png)

**Comment by allthesignals** [comment]
What's the solution for this? Is it a new annotation tool option to draw arrows (cant' remember if that exists or not)? Or maybe it's an option fo rthe CL icon?

**Comment by trbmcginnis** [comment]
Working on this in branch 383-centerline-annotation

https://github.com/NYCPlanning/labs-applicantmaps/tree/383-centerline-annotation
