### ISSUE TITLE
Add pattern filled commercial overlays layergroup

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#39]

**Comment by allthesignals** [comment]
Would love to see how this works @andycochran

**Comment by andycochran** [comment]
PR in Layers API adds the layer group w/ new pattern styles https://github.com/NYCPlanning/labs-layers-api/pull/57

**Comment by andycochran** [comment]
Just need to add the `commercial-overlay-patterns`layer group to this app.
