### ISSUE TITLE
Annotations don't show up on area map

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#391]
Steps to reproduce:
- Create a project
- Add a free form text label annotation on one of the rezoning maps
- See that the text label you've created doesn't show up on the area map

**Comment by andycochran** [comment]
This should've been resolved in #377 / #432. Let's confirm then close this.

**Comment by allthesignals** [comment]
I can confirm this is happening on staging over here: https://applicantmaps-staging.planninglabs.nyc/projects/MuUErZQjTDMB4T704Kn1

There may be some incoming PRs that close this, however, let's treat this issue as a bug, and therefore something worth adding a test for.
