### ISSUE TITLE
Users find it unclear what to do on dashboard

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#399]
The dashboard should make it more clear that you’re done and reviewing what you created (“does this all look correct?”) and can now download the map

**Comment by andycochran** [comment]
Have any thoughts on this redesign? @hannahkates 
![image](https://user-images.githubusercontent.com/409279/53111225-b7bbe400-350a-11e9-9b79-252922fb9d6e.png)

**Comment by andycochran** [comment]
Per @hannahkates' suggestions… 
![image](https://user-images.githubusercontent.com/409279/53112615-a58f7500-350d-11e9-9995-46f61433c1f5.png)
