### ISSUE TITLE
While defining their study area, applicant can search for an address or BBL

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#4]

**Comment by allthesignals** [comment]
Gonna wait for wireframes before attempting to close this

**Comment by andycochran** [comment]
This issue adds the `labs-ember-search` addon. 

Depends on #18.

**Comment by chriswhong** [comment]
Add `labs-search` component

**Comment by allthesignals** [comment]
Should this float over the map or sit somewhere else? Position matters because there are a few different scopes to put this in, and that will affect how the threading of state works
