### ISSUE TITLE
Users want better data citations on area map

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#404]
The data citations should be captured more formally and include data version numbers, especially for PLUTO. PLUTO version number is important for knowing whether a map may need to be updated.

**Comment by trbmcginnis** [comment]
I think we shortened this from the original format to better fit the inset map. When we add in `meta.description` from labs-layers-api, it gives us a much more formal citation but adds a lot of text, squishing the inset map in portrait + letter mode. 

![citation_applicant_maps.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1a8ed004e6dd00118290e2/125516c66e82c728ace21e0d46eb9d8e22968aa681d6be53b451f9972848334c2405b33832c9a138ad4d71040c1b5ca6535d0d45f9fcd829f0b53c24db555fedd16f5a20c13916afed9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3b1f041a8afb5e3da0904cda15.png)
