### ISSUE TITLE
Zoning districts and their labels aren't showing up on area map

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#407]
This is an issue where zoning layers are only being fetched and displayed on the final map if the user said they need to edit that layer. All existing zoning should be fetched and displayed on the area map.

**Comment by allthesignals** [comment]
> zoning layers are only being fetched and displayed on the final map if the user said they need to edit that layer

^ do you mean they are only displayed if they previously worked through the "add a rezoning layer" dialogue during the previous steps?

**Comment by allthesignals** [comment]
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/5004319/53349195-8e280180-38ea-11e9-85c2-77e5035bae6a.png">
^ it looks like this is wrong, then? According to the legend, there should be _something_ styled?

**Comment by hannahkates** [comment]
If layer doesn't exist in mode, grab it from layers-API
