### ISSUE TITLE
Users want reset original default button for geom editing

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#412]
If you accidentally delete a zoning district, you can't get it back. We need an undo or reset button.

**Comment by hannahkates** [comment]
Based on discussion with TRD yesterday, a button that resets to the original zoning should be sufficient. Another related issues we noticed was that if you move a zoning boundary line ever so slightly (trying to get it back to where it originally was), the rezoning area calculation still detects it and shows the dashed line. A reset button would solve this problem

**Comment by hannahkates** [comment]
Some helpful watch outs from the last attempt at this are in #271.

**Comment by allthesignals** [comment]
Definitely a big ask but not impossible. I've researched several options for this, I think I documented this in an issue or branch somewhere. Will need time to dig that up. There are some addons that handle the memorization for undo behavior

**Comment by allthesignals** [comment]
@hannahkates is this a new button on the rezoning steps?

**Comment by allthesignals** [comment]
When we figure which buttons go where, all that needs to be done is that it calls `setCanonical()` on the model.
