### ISSUE TITLE
Increase logging output from applicantmaps-api & persist

### ISSUE THREAD

**Issue by julialucyhogan** [NYCPlanning/labs-applicantmaps#416]
This should be moved to https://github.com/NYCPlanning/labs-applicantmaps-api, but the gist is to improve the handling for error logging, output, noise reduction, persistence, etc. 

Promise - and error catching - in Express isn't perfect - sometimes errors get swallowed up. 

https://github.com/NYCPlanning/labs-applicantmaps-api/blob/develop/store.js#L7-L17 
^ this project uses Forture, which is an opinionated "magic" convention-based framework for implementing a RESTful JSON API-compliant resource service. This means a lot of hardwiring is taken care of but also we may need to dig more into FortureJS documentation and internals to understand if and how errors get swallowed.

**Comment by julialucyhogan** [comment]
I dont exactly remember opening this issue :) but given that there's so much actual feature/bug work to do, I'm not sure this should/can be prioritized this sprint.

**Comment by andycochran** [comment]
Let's move it back to the inbox?

**Comment by julialucyhogan** [comment]
Having now actually taken another look at this backend, there is literally exactly one potential failure path. Previously, we were not logging out this error. In early Feb, I merged a commit to add logging of that caught error. Not much else to do here. 

and, logs are indeed in paper trail! 

Task of setting up a more long-term and easily queriable log stack (ELK?) still exists, but is outside the scope of this ticket. I am marking closed.
