### ISSUE TITLE
Users shouldn't be able to save new zoning district without labeling it

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#417]
In user testing, a user was able to create and save a new commercial district without selecting a label for it. The model should require them to select a label before being able to save. The zoning district label box should also be more obvious, maybe with red highlighting, so the user's visual attention is more drawn to this required step.

**Comment by andycochran** [comment]
Related to #380. If we decide to always save everything on change, we need to some validation to indicate that the geom has no label. Perhaps the yellow popup with the dropdown should be red to indicate an error unless the geom is labeled.

**Comment by allthesignals** [comment]
I think the short term solution: 

1. Make the model validate the label
2. Hook into the "isReadyToProceed" check in types.js to prevent movement.
