### ISSUE TITLE
User didn't find the "tag" icon for the zoning district label box to be instructive

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#420]
The user didn't think this icon was a clear prompt to select a label. We could use explicit working instead. 
![image](https://user-images.githubusercontent.com/13967925/52672690-8fb9f880-2eec-11e9-990b-bff0f70b642f.png)

**Comment by allthesignals** [comment]
What's the ask here? Can't comment on complexity without a design solution.
