### ISSUE TITLE
Reviewers should see sidewalks and transportation structures

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#422]
These two layers have zoning implications and provide context for reviewing a proposed project.

Data is available via Planimetrics:
- https://data.cityofnewyork.us/City-Government/Sidewalk/vfx9-tbb6
- https://data.cityofnewyork.us/City-Government/Transportation-Structures/h9sf-7bej

The two layers will need to be added to the layers API and the area map.

**Comment by allthesignals** [comment]
This means adding new non-interactive context layers to the area map alone, right?

**Comment by trbmcginnis** [comment]
@hannahkates Is there a specific reason we wanted to use the planimetrics version of transportation-structures over citymap?

**Comment by hannahkates** [comment]
@trbmcginnis I don't think there's a particular reason. It just might be simpler for both layers to come from planimetrics, but if the streets data seems to have it all, I think that's fine.

**Comment by trbmcginnis** [comment]
awesome thanks!
