### ISSUE TITLE
Users want map zoom levels to reflect their area of interest

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#433]
- [ ] When searching for an address or BBL, users want the map to zoom in closer to that location.
- [ ] When editing underlying zoning boundaries, the map starts out too zoomed in for them to see enough context. It should default to a lower zoom number.

**Comment by allthesignals** [comment]
The first checkbox sounds like just make the zoom closer? Same with the second, just not as zoomed in

**Comment by julialucyhogan** [comment]
@hannahkates  @allthesignals for the second ask: does this mean the circle we draw around the project area should also be increased? Or should we just zoom to something that fits inside that circle?
