### ISSUE TITLE
After viewing area map, zoning layers appear on dashboard map

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#502]
Steps to reproduce:
1. Create a project comprised of only a development site
2. Once you arrive on project dashboard, see that the map shows only the development site, as expected
2. View area map
3. Click "back to project"
4. See that zoning layers now appear on the dashboard map when they shouldn't. If you go back to edit your development site, the zoning layers will also appear on that geom-edit route.

**Comment by hannahkates** [comment]
This is related to these changes: https://github.com/NYCPlanning/labs-applicantmaps/commit/4c6c0b66c07bb3957099c2c89d62e8abd6c95341

**Comment by allthesignals** [comment]
This is happening because the `project-geometry-renderer` component shows underlying zoning geometries if they exist on the model. Zoning data can exist on the model without the model actually needing it.

**Comment by allthesignals** [comment]
Closed by #556

**Comment by allthesignals** [comment]
I screwed something up in commit history. There's a test for this, but can someone confirm on staging? @hannahkates
