### ISSUE TITLE
[Annotations] Arrow doesn't show up until user draws another annotation

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#504]
When a user draws their **first annotation**, the arrows will not fully show up (sometimes there's one arrow, sometimes there's none). 

**Zooming** in and out will make the arrows disappear and reappear. 

The arrows on that first annotation will **show up permanently** when:
- User draws another annotation
- User relabels a zoning district

**Comment by trbmcginnis** [comment]
**An example where no arrows showed up:**

![Screen Shot 2019-03-15 at 10.58.08 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1a8ed004e6dd00118290e2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f66b7191a379ef0c2e59415f46bc30254d58eeb9cb74fce36f34985619e8836c5a71973f47afb8d64eb655ba20894ad1b1b88d4f95fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ee34b53a51a3562e772316e0a.png)

**Comment by hannahkates** [comment]
They also appear/disappear depending on the zoom level, without drawing a new annotation. See gif below
![Mar-15-2019 11-28-13](https://user-images.githubusercontent.com/13967925/54442687-7982a080-4715-11e9-949c-5734248ffca5.gif)

**Comment by julialucyhogan** [comment]
oh weird! maybe this can be fixed with just styling ! great catch, @hannahkates

**Comment by chriswhong** [comment]
I believe this is due to the image for the arrowhead not being added to the map in time.  

The icon gets added using https://docs.mapbox.com/mapbox-gl-js/api/#map#addimage, I am not sure how, but I think we need to confirm that it's available before trying to render things that use it.

**Comment by hannahkates** [comment]
Closing, looks like this was fixed successfully.
