### ISSUE TITLE
Revise and confirm models and routes

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#51]

**Comment by hannahkates** [comment]
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593ac159e983f40020992a93/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65262b55f67e71d7e57bef467a580b5f4eae440c5840fbfadc39baa47e21d40854b088270a36d43703adbf881eba02bd238d488cb7ba884ec2fa70.png)

**Comment by chriswhong** [comment]
"Project Dashboard" should be /projects/:id (not /projects/:id/edit)
projects/:id/edit should be the same view as the initial project creation screen
