### ISSUE TITLE
When user clicks back button after exiting projects/new, draw button doesn't work

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-applicantmaps#53]

**Comment by trbmcginnis** [comment]
Replicate bug:

-go to route projects/new
-fill in form and draw a polygon
-click on "create project" button
-once brought to new page, hit back button
-try to use draw tool again (does not allow to draw, instead gives hand cursor)

**Comment by hannahkates** [comment]
Should no longer be an issue with refactor of geom creation work flow
