### ISSUE TITLE
Should the Rezoning Area be able to have donut holes? 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#539]
If you change the name of a zoning area that has a hole, the auto-generated Rezoning Area will also have holes. If I understand correctly, the Rezoning Area is meant to contain all changes, and the holes are not necessary.  

![image](https://user-images.githubusercontent.com/409279/57301656-82557a00-70a7-11e9-9a8b-11d781e7d788.png)

**Comment by allthesignals** [comment]
Can you help me understand the urgency of this? Also, not a bug.
