### ISSUE TITLE
Can't delete zoning

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#540]
On the dashboard, if you click the trash icon to delete Underlying Zoning, Commercial Overlays, or Special Purpose Districts they are removed from the map. However, if you then refresh the project, any zoning you deleted comes back.

**Comment by julialucyhogan** [comment]
@andycochran  @hannahkates should a user be able to delete the project area (and maybe also development site) from the final dashboard? Project without project area is invalid. Thoughts?

**Comment by hannahkates** [comment]
Not all projects require project areas, but they all require a development site. I think they shouldn't be able to delete the development site. Deleting the project area is fine.

**Comment by allthesignals** [comment]
Closed by #540
