### ISSUE TITLE
Production app isn't loading

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#543]
Console:
0:252 Uncaught Error: Could not find module `ember-compatibility-helpers` imported from `ember-concurrency/-task-property`

**Comment by allthesignals** [comment]
https://github.com/machty/ember-concurrency/issues/285

**Comment by allthesignals** [comment]
Struggling to reproduce locally... 

Blowing out node_modules and starting over. Probably need to version bump something. Going to try to form yarn to resolve to a specific version of ember-concurrency (which gets around this problem).

**Comment by allthesignals** [comment]
Version bumps have introduced new deprecation warnings in the console. These should be addressed to keep this app primed for major upgrades in the future.

**Comment by allthesignals** [comment]
Closed by #544
