### ISSUE TITLE
Wizard: Projects with only a Development Site show the Rezoning Q after complete

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#562]
Having trouble reproducing this, but both @allthesignals and I saw this happen. 

If you… 

- Create a new project
- Add a Development Site
- Say "No" to the Project Area question
- Say "No" to the Rezoning question
- Click "Go to Project Dashboard" 

…you're shown the Rezoning question again.

**Comment by andycochran** [comment]
Need to verify if this is still an issue.

**Comment by hannahkates** [comment]
Closing. Tried reproducing on different computers on 4/10 and this was no longer a problem
