### ISSUE TITLE
BUG - "Alter Zoning" button not live/responding

### ISSUE THREAD

**Issue by zpaulpower** [NYCPlanning/labs-applicantmaps#575]
@hannahkates, the "Alter Zoning" button on the attached wasn't live/active when I went to do a test project.
thanks,
PHP
![Applicant Maps issue](https://user-images.githubusercontent.com/40032623/63452341-0b54af00-c414-11e9-813c-1f6d27c2ce1c.JPG)

**Comment by hannahkates** [comment]
The "Alter Zoning" button doesn't become active until you fill in all the radio buttons for the question asking which layers you want to edit. If you click No for Special Purpose Districts, you'll then be able to click the button.
