### ISSUE TITLE
Major Issue with map not showing correct zoning district/district boundaries. 

### ISSUE THREAD

**Issue by vvvo** [NYCPlanning/labs-applicantmaps#579]
The map I just made in queens shows inaccurate data. 

See applicant map: [https://applicantmaps.planning.nyc.gov/projects/7XWv0JBa8PnhaQx8PJD9/edit/map/edit](https://applicantmaps.planning.nyc.gov/projects/7XWv0JBa8PnhaQx8PJD9/edit/map/edit)

See accompanying zoning sectional map for reference: 
[Zoning Sectional Map_Zoomed In.pdf](https://github.com/NYCPlanning/labs-applicantmaps/files/4278671/Zoning.Sectional.Map_Zoomed.In.pdf)

**Comment by allthesignals** [comment]
Thanks @vvvo — I'm sorry but what is missing from the applicant map link? Is the data current on [ZoLa](https://zola.planning.nyc.gov/about?layer-groups=%5B%22building-footprints%22%2C%22street-centerlines%22%2C%22subway%22%2C%22tax-lots%22%2C%22zoning-districts%22%5D)? Do you think the data is outdated?

**Comment by vvvo** [comment]
I think the applicant map data might be outdated - it's missing R7A, R7X, & R3-2 (which is correctly shown in ZoLa map below.
![Missing Data](https://user-images.githubusercontent.com/43350235/75993208-2033f400-5ec7-11ea-9374-df785ee97a1f.PNG)

**Comment by allthesignals** [comment]
That's @vvvo, that's very helpful.

This may be pointing to outdated data.

@hannahkates do you have any insight here?

SQL query is consistent across:
```sql
SELECT cartodb_id AS id, * FROM (SELECT the_geom_webmercator, zonedist, CASE WHEN SUBSTRING(zonedist, 3, 1) = '-' THEN LEFT(zonedist, 2) WHEN SUBSTRING(zonedist, 3, 1) ~ E'[A-Z]' THEN LEFT(zonedist, 2) WHEN SUBSTRING(zonedist, 3, 1) ~ E'[0-9]' THEN LEFT(zonedist, 3) ELSE zonedist END as primaryzone, cartodb_id FROM zoning_districts) a
```

That said, ZoLa points to https://labs-layers-api.herokuapp.com/v1/layer-groups and Applicant Maps points to https://layers-api.planninglabs.nyc/v1/layer-groups.

This may be the source of the issue. I'll dig in a bit more.

**Comment by allthesignals** [comment]
Scratch all that, this is why: https://github.com/NYCPlanning/labs-applicantmaps/blob/d61a4d40e821632516a0a654721310dc8cf678d0/app/utils/queries/intersecting-zoning-query.js#L26

It is pointing to an outdated version of zoning! Will push a fix asap.

**Comment by allthesignals** [comment]
<img width="438" alt="Screen Shot 2020-03-05 at 2 40 38 PM" src="https://user-images.githubusercontent.com/5004319/76019209-55543c80-5eef-11ea-8cbe-f086d6ca0d64.png">

Confirming that the deploy preview of my patch shows the updated zoning geometries. @vvvo does this look right? We'll try to get this deployed ASAP.

I believe you can "refresh" by going in and visiting the rezoning step.

**Comment by allthesignals** [comment]
@vvvo wanted to follow up on this

**Comment by vvvo** [comment]
Yep looks right. Thanks Matt!

**Comment by vvvo** [comment]
Hey Matt, I'm trying to redo this map again and the same issue is popping up (map showing old zoning districts).

**Comment by allthesignals** [comment]
@vvvo did you create a new project entirely? or you are refreshing it?

**Comment by allthesignals** [comment]
@vvvo sorry about that i think we need to deploy the new code
