### ISSUE TITLE
Decide how the 600 ft buffer boundary should be styled

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#63]

**Comment by andycochran** [comment]
https://www1.nyc.gov/assets/planning/download/pdf/applicants/applicant-portal/
https://www1.nyc.gov/assets/planning/download/pdf/applicants/applicant-portal/area_map_land_use_and_zoning_sample1.pdf

^ These two sample maps visualize it differently. What should it be?
