### ISSUE TITLE
Sample Map Attachment Package

### ISSUE THREAD

**Issue by vvvo** [NYCPlanning/labs-applicantmaps#70]
Example of all 4 attachments.

**Comment by vvvo** [comment]
[SAMPLE - Map Attachments (With Rezoning).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9fe10e74e7c500126c1adb/125516c66e82c728ace21e0d46dbb5b713aea6e9c2a99242b41dd1803d47247b2401ad3f63c5ab1fb65673413d0a04f31f010113e5eb9539e6f4632adf0f4fffdb7f5a26c73814fdbad41cbf55eb29df4f85b4b9de4bc4ef3e70f5979d0d6f405147d4a61760e28b41da59f141e04856a3163262e377357d41970c38.pdf)

**Comment by hannahkates** [comment]
Stored on google drive for future reference
