### ISSUE TITLE
Project Dashboard UX Improvements

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#77]
Currently these are labeled with the project ID integer instead of the map type

**Comment by chriswhong** [comment]
- [ ] Maps are 1 to 1, so indicate which have been created, and which have not.
- [ ] Get rid of "existing maps"/ "Add new Map",
- [ ] For maps that have been created, show a thumbnail

**Comment by allthesignals** [comment]
How should this look?
