### ISSUE TITLE
Switch building footprints to thin line

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicantmaps#83]
It's hard to see the difference between a building footprint and shaded special district boundary. Building footprints should be an outline so it is easier to discern against the special district shading

**Comment by allthesignals** [comment]
This sounds like a app-wide style change, yes?

**Comment by trbmcginnis** [comment]
we have a `building-footprints` layer-group in the app but even when removed the our OpenMapTiles version of the basemap (Positron) has a buildings layer https://layers-api-staging.planninglabs.nyc/v1/base/style.json, so need to either edit this layer or remove it and then edit the layer-group.
