### ISSUE TITLE
Applicant is walked through the process of creating multiple maps (wizard)

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-applicantmaps#9]

**Comment by hannahkates** [comment]
Why shouldn't all possible maps be generated automatically for all users?

**Comment by chriswhong** [comment]
I believe it depends on the type of application, not all maps are required for every application.

**Comment by hannahkates** [comment]
Gotcha, ok then I can definitely see the value in a wizard that also helps coach applicants through identifying which maps are required depending on their proposed activity.

**Comment by hannahkates** [comment]
In progress - closing in favor of more discrete issues.
