### ISSUE TITLE
Area Map Tweaks

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#98]

**Comment by chriswhong** [comment]
- [ ] Legend items are reversed (Development Site x Project Area)

**Comment by andycochran** [comment]
^ All these in one issue feels wrong. These aren't all "tweaks."

**Comment by andycochran** [comment]
> Make development site line black when it's covered in red/commercial land use color

The development site line _is_ black.

**Comment by andycochran** [comment]
Working on branch `98-area-map-tweaks`…

**Comment by andycochran** [comment]
PR #134 has commits to handle what's checked. I'm going to move the other items to their own issues…
