### ISSUE TITLE
User can create/edit Proposed Zoning

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-applicantmaps#99]

**Comment by allthesignals** [comment]
Any movement on this one? Seems like there's a research/design step

**Comment by chriswhong** [comment]
I think it all depends on whether the approach for tax maps is to overlay on the "official" PDFs, or to make our own tax map from the data.

I explored the latter this week, which would mean drawing happens in a map-based drawing tool (mapboxGL-draw)

If we go a different route (non-mapping), there are probably existing drawing packages we could use to overlay an SVG on top of the tax map PDF.

**Comment by chriswhong** [comment]
On the Project Form, we need: 
- another drawing tool that allows the user to edit the zoning districts
- another drawing tool that allows the user to edit the special purpose districts

These can work by clipping the existing data for each, and providing it as an editable layer that can be modified with leaflet draw.

- [ ] Figure out labels.  If we stick with polygons for zoning districts, we get labels for free.  If we break them up in to line segments, labels get trickier.

**Comment by chriswhong** [comment]
- [  ] User can add existing zoning districts based on a buffer around the project's development site
- [  ] User can enter an edit mode, drag vertices, and modify existing zoning district boundaries
- [  ] User can edit the `zonedist` property for a selected zoning district polygon when in edit mode
- [  ] User can scrap the entire set of zoning polygons associated with the project and start fresh

- [  ] UX Improvements and Styling by @andycochran
